### ISSUE TITLE
Check if proper React patterns are used (very unlikely) and refactor if necessary 

### ISSUE THREAD

**Issue by aawgit** [aawgit/signs-web#9]

**Comment by dadolhay** [comment]
Hey @aawgit,

I'd be happy to take a look at this!

Would you want me to also add `prettier` and `eslint`?

**Comment by aawgit** [comment]
Hi @dadolhay Thanks. I'm assigning this to you. Yes feel free to add.

**Comment by dadolhay** [comment]
Hey @aawgit,

I already submitted a PR for this

**Comment by aawgit** [comment]
Sorry I didn't notice. Merged it. Thanks.
